const products = [
  {
    '_id': '1',
    'name': 'It',
    'image': '/images/airpods.jpg',
    'description':
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    'publishing': 'Pearson',
    'category': 'Novel',
    'price': 89.99,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
    'author': 'Stephen King',
    'genre': 'Horror',
    'numOfPages': 450,
  },
  {
    '_id': '2',
    'name': 'Harry Potter',
    'image': '/images/phone.jpg',
    'description':
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    'publishing': 'Pearson',
    'category': 'Novel',
    'price': 599.99,
    'countInStock': 7,
    'rating': 4.0,
    'numReviews': 8,
    'author': 'Joanne K. Rowling',
    'genre': 'Fantasy',
    'numOfPages': 334,
  },
  {
    '_id': '3',
    'name': 'I Robot',
    'image': '/images/camera.jpg',
    'description':
      'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
    'publishing': 'Old Lion',
    'category': 'Novel',
    'price': 929.99,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
    'author': 'Isaac Asimov',
    'genre': 'Sci-fi',
    'numOfPages': 221,
  },
  {
    '_id': '4',
    'name': 'Kateryna',
    'image': '/images/playstation.jpg',
    'description':
      'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
    'publishing': 'Letter Publishing',
    'category': 'Novel',
    'price': 399.99,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 12,
    'author':'Taras Shevchenko',
    'genre':'Poem',
    'numOfPages':145,
  },
  {
    '_id': '5',
    'name': '1984',
    'image': '/images/mouse.jpg',
    'description':
      'Get a better handle on your games with this Science LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
    'publishing': 'Science',
    'category': 'Novel',
    'price': 49.99,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
    'author':'George Orwell',
    'genre':'Dystopian',
    'numOfPages':225,
  },
  {
    '_id': '6',
    'name': 'Introduction To Algorithms',
    'image': '/images/alexa.jpg',
    'description':
      'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
    'publishing': 'Basis',
    'category': 'Novel',
    'price': 29.99,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 12,
    'author':'Thomas Cormen',
    'genre':'Non-Fiction',
    'numOfPages':950,
  },
]


export default products
